defaults:
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
  - _self_

model:
  model_id: "Wan-AI/Wan2.1-T2V-1.3B-Diffusers"
  torch_dtype: "bfloat16"
  negative_prompt_path: "${hydra:runtime.cwd}/prompts/video_generation/negative_prompt.txt"

video:
  quality:
    resolution: "480p"  # or "720p"
    dimensions:
      "480p":
        height: 480
        width: 848
      "720p":
        height: 720
        width: 1280
    flow_shift:
      "480p": 3.0
      "720p": 5.0
  fps: 16
  num_frames: 61  # num_frames -1 needs to be divisible by 4
  guidance_scale: 5.0

paths:
  prompts_path: "${hydra:runtime.cwd}/prompts/video_generation/prompts/benchmark.json"
  output_dir: "${hydra:runtime.cwd}/results/video_generation"
  output_prefix: "wan_video"

hydra:  
  output_subdir: null  
  run:  
    dir: .